pipeline_id: github_commits
description: "Ingests repository commits from GitHub API with watermark-based incremental loading (Local Development)"
enabled: true
extractor_class: "api_pipeline.extractors.github_commits.GitHubCommitsExtractor"

api_config:
  base_url: "https://api.github.com"
  endpoints:
    commits: "/repos/{owner}/{repo}/commits"
  auth_type: "bearer"
  auth_credentials:
    token: "${LOCAL_GITHUB_TOKEN}"  # Will be loaded from .env file
  rate_limit: 30  # Lower rate limit for local testing
  retry_count: 2
  batch_size: 30  # Increased for better performance
  max_concurrent_requests: 10  # Increased for better performance
  session_timeout: 10
  
  # Watermark configuration
  watermark:
    enabled: true
    timestamp_field: "committed_at"
    watermark_field: "last_commit_watermark"
    window:
      window_type: "fixed"
      window_size: "24h"     # Increased window size for fewer API calls
      window_offset: "0m"
      timestamp_field: "committed_at"
    lookback_window: "1d"    # Shorter lookback for local testing
  
  # Pagination configuration
  pagination:
    enabled: true
    strategy: "page_number"
    page_size: 100          # Increased to GitHub's max page size
    max_pages: 2            # Limited pages for faster testing
    page_param: "page"
    size_param: "per_page"

parameters:
  - name: "repo"
    type: "string"
    required: true
    description: "GitHub repository in format owner/repo"
    default: "apache/spark"  # Default for testing
  - name: "branch"
    type: "string"
    required: false
    description: "Branch to fetch commits from"
  - name: "author"
    type: "string"
    required: false
    description: "Filter commits by author"

output:
  - type: "bigquery"
    enabled: false  # Disabled for local development
    config:
      project_id: "local-dev"
      dataset_id: "raw_data_local"
      table_id: "github_commits"
      schema:
        - name: "commit_id"
          type: "STRING"
        - name: "repo_name"
          type: "STRING"
        - name: "author_name"
          type: "STRING"
        - name: "author_email"
          type: "STRING"
        - name: "message"
          type: "STRING"
        - name: "commit_url"
          type: "STRING"
        - name: "committed_at"
          type: "TIMESTAMP"
        - name: "files_changed"
          type: "INTEGER"
        - name: "additions"
          type: "INTEGER"
        - name: "deletions"
          type: "INTEGER"
        - name: "processed_at"
          type: "TIMESTAMP"

  - type: "local_json"  # Primary output for local development
    enabled: true
    config:
      output_dir: "./data/github/commits"
      file_format: "jsonl"
      partition_by: ["date", "repo"] 